### ISSUE TITLE
Feature Request: Support customizing citation syntax

### ISSUE THREAD

**Issue by wenlzhang** [chrisgrieser/alfred-bibtex-citation-picker#1]
### Feature Requested

Currently, the default citation syntax is `[@citekey]`, for use with pandoc. In my workflow, there are also two other use cases.

- In Obsidian notes, sometimes I would like to insert the citation key as tags, e.g. `#citekey`. This way, I can easily see where a paper is referenced from the tag pane and graph view.
- When writing in LaTeX, I may use the citation key in the format `\cite{citekey}`.

Therefore, it would be great if one can customize the citation syntax to use. For instance, one can set a default format and a few other formats. When inserting the citation key, the default format would be used, unless specified otherwise.

### Checklist

- [X] The feature would be useful to more users than just me.

**Comment by noirchen** [comment]
I agree. This can be implemented as an option choosing between @, # or bare key.

**Comment by owlasea** [comment]
Seconded. This would be super useful! Thanks!

**Comment by stravers56** [comment]
I would like this feature for latex as well.

**Comment by chrisgrieser** [comment]
Can anyone refer me to some documentation for Latex citations? Specifically, I need information on how citations look like for various cases?
- single citation with page numbers
- multiple citations without page numbers
- multiple citations with page numbers

**Comment by owlasea** [comment]
> 

These are the ones that work for bibtex. Not sure if it works for other settings/packages (e.g., Natbib, apacite).

- Single citation with page numbers: \cite[pageNumber]{citekey}
- Multiple citations without page numbers: \cite{citekey1, citekey2, citekey3}
- Multiple citations with page numbers: \citetext{\citealp[pageNumber1]{citekey1}; \citealp[pageNumber2]{citekey2}.....}


I also found these on Overleaf for your reference:
https://www.overleaf.com/learn/latex/Biblatex_citation_styles

https://www.overleaf.com/learn/latex/Natbib_citation_styles

**Comment by chrisgrieser** [comment]
so instead of hardcoding a citation syntax format, I have simply turned all of them into variables, so it should cover everything form tags in Obsidian to other citation formats. However I am not totally certain, that I "get" the weird Latex citation syntax – would this suffice? (the screenshot contains the values for Pandoc citations)

You can try it out in release 9.0.0.

<img width="252" alt="Pasted image 2022-05-19 19 56 20" src="https://user-images.githubusercontent.com/73286100/169369245-23786551-acb8-4568-b683-6e108373139b.png">

**Comment by owlasea** [comment]
> 

Thanks for the great work Chris! Everything works except the _format_citekey_prefix though. When I set it to empty instead of @, the "@" still appears anyway. If I change it to other values, @ remains and the newly set value is not reflected. Wonder if there is anything I am doing wrong? Should I be tweaking something else? Thank you again!

**Comment by noirchen** [comment]
Thanks for the new version! Everything works like a charm. I did not meet the persisting @ issue.

**Comment by owlasea** [comment]
Ah I reloaded the buffer and now everything works!

**Comment by chrisgrieser** [comment]
Could you show me what values you have all set for `_format...` ?

That way, I can add some presets, which not only make it easier to switch, but also automatically reload the buffer

**Comment by chrisgrieser** [comment]
also, I noticed that with certain citation styles, you put the page number *before* the citekey. So I have added the following two options to version 9.1.0 to account for that possibility.

Could you give it a try and see whether you can cover all cases (multiple citations, with/without page numbers) by having these variables? If those are enough, and you can give me the values for the `_format...` variables, then I can set presets so the user doesn't have to fiddle too much with the formatting.

![image](https://user-images.githubusercontent.com/73286100/169468416-d1ab2fe8-d7e8-46a8-82fb-ff5430016cfc.png)

**Comment by owlasea** [comment]
Hi @chrisgrieser , here is the values I set for _format...:
<img width="275" alt="Screen Shot 2022-05-20 at 15 09 13" src="https://user-images.githubusercontent.com/46643874/169473161-5921b4db-5dda-45ac-bdb1-b6800892583c.png">

I also noticed that the reason that reloading the buffer solves the issue with persistent @ is that I have set the prefix to empty in the first place, but this creates another problem that, if I want to insert something like [[@citekey]] and the prefix is set to empty, it will give me [[citekey]] without the @. 

For now I am using this workaround: I added another step (indicated by the yellow arrow in the pic below) between "ct" and "copy to clipboard" (where only {query} is pasted). If the command key is pressed, it will lead to another copy to clipboard action, where {var:_format_citation_start}{var:_format_citekey_prefix}{query}{var:_format_citation_end} is pasted, as shown in this pic with the blue arrow.

**Comment by chrisgrieser** [comment]
> if I want to insert something like [[@citekey]] and the prefix is set to empty, it will give me [[citekey]] without the @

@owlasea I am not entirely sure that I understand what you mean. Like, how is `set prefix → get prefix` not the intended behavior? 🤨 

If this is about the need for reloading, I just pushed an update (9.1.2) which removes the prefix from the query, so that you can change the formatting without reloading the buffer.

**Comment by chrisgrieser** [comment]
with 9.2.0, one can now more conveniently change the citation format via `scp`. You can add citations formats, e.g. for all the Latex variants, [via PR to this file](https://github.com/chrisgrieser/alfred-bibtex-citation-picker/blob/main/toggle-citation-format.js).

<img width="1060" alt="Pasted image 2022-05-20 12 02 32" src="https://user-images.githubusercontent.com/73286100/169505400-301f8d44-8b3a-4a20-8054-3c61db54ca87.png">
<img width="1056" alt="Pasted image 2022-05-20 12 02 54" src="https://user-images.githubusercontent.com/73286100/169505427-11b9b4b4-0340-4e20-80f8-15313e8227d1.png">

**Comment by owlasea** [comment]
This is awesome! Thanks Chris!

By the way is the multiple citation working properly? I am getting something like this:
<img width="213" alt="Screen Shot 2022-05-20 at 21 17 33" src="https://user-images.githubusercontent.com/46643874/169536159-9959e561-d960-4541-af5a-e53343c5280c.png">

The only citation that gets the prefix is the one that I select last? Was not a problem in some earlier versions.

**Comment by chrisgrieser** [comment]
thanks, is fixed

**Comment by chrisgrieser** [comment]
just for reference: I also added a bare citekey option. 

With the irregularity of Latex citations, I'd probably need some advice on how to properly format that. In case someone is interested in that, please open a new issue for the Latex citation format
