### ISSUE TITLE
Feature Request: Open entry in Zotero option

### ISSUE THREAD

**Issue by kenanmike** [chrisgrieser/alfred-bibtex-citation-picker#14]
### Feature Requested

Is it possible to set open_entries_in to Zotero? I've tried doing it myself but as an ignoramus I've been unsuccessful!

### Checklist

- [X] The feature would be useful to more users than just me.

**Comment by chrisgrieser** [comment]
that wouldn't be a problem, I think. As I am not a zotero user myself, could you confirm that `zotero://select/items/@[citekey]` works to reveal an entry in Zotero?

**Comment by kenanmike** [comment]
Yes it works with @citekey (no brackets or square brackets). Thanks!

> that wouldn't be a problem, I think. As I am not a zotero user myself, could you confirm that `zotero://select/items/@[citekey]` works to reveal an entry in Zotero?

**Comment by chrisgrieser** [comment]
okay than, feature added in release 10.0.9 :)
