### ISSUE TITLE
[Bug]: Can not list the result if the input has `-`

### ISSUE THREAD

**Issue by WeiViming** [chrisgrieser/alfred-bibtex-citation-picker#17]
### Bug Description

Hello, I found that no result return if my input has symbol (e.g. `-`), even though the bibtex entry exists. See the screenshot (I change `ct` to `zt` for this workflow).

Is it possible to fix it? Thank you.

Best regards,

Viming

### Relevant Screenshot

<img width="718" alt="image" src="https://user-images.githubusercontent.com/35755899/197216346-4ea30dd7-6ccb-4a5d-a749-77d37697da79.png">

### Debugging Log

```Text
No response
```

### Sample BibTeX Entries

```BibTeX
@incollection{Okamoto_1998_new,
  title = {A new public-key cryptosystem as secure as factoring},
  booktitle = {Advances in Cryptology \textemdash{} EUROCRYPT'98},
  author = {Okamoto, Tatsuaki and Uchiyama, Shigenori},
  year = {1998},
  volume = {1403},
  pages = {308--318},
  doi = {10.1007/BFb0054135},
  language = {en}
}
```

### Buffer Files

No response

### Workflow Configuration

No response

### Checklist

- [X] I have [updated to the latest version](https://github.com/chrisgrieser/shimmering-obsidian/releases/latest) of this workflow.
- [X] I have tried manually reloading the buffer (Alfred keyword `scp`, select `Force Buffer Reload`).

**Comment by chrisgrieser** [comment]
thx, fixed in the latest release 10.0.14
