### ISSUE TITLE
Feature Request: Auto Update

### ISSUE THREAD

**Issue by ShangWangNUST** [chrisgrieser/alfred-bibtex-citation-picker#2]
### Feature Requested

Dear developer，

Vitorgalvao has built an alfred-workflows namely OneUpdater（https://github.com/vitorgalvao/alfred-workflows/tree/master/OneUpdater）. Is it possible to integrate it into your workflow? This can be upgraded automatically.

Thank you for your awesome work!

### Checklist

- [X] The feature would be useful to more users than just me.

**Comment by chrisgrieser** [comment]
It ahead is integrated!
