### ISSUE TITLE
[Bug]: fail to add another page when pressing opt+enter

### ISSUE THREAD

**Issue by u2003** [chrisgrieser/alfred-bibtex-citation-picker#22]
### Bug Description

Thank you for helping out with the last issue!
Yet still a little problem. I find strange things occur every time I press opt+enter on an entry, no pop-up window, nothing is copied, but it jumps to the Finder (as you can see in the gif).

### Relevant Screenshot

![CleanShot_2023-01-18_211814](https://user-images.githubusercontent.com/84957135/213184425-0909c6c6-40cd-4d79-8136-3a6ec1d0f225.gif)

### To Reproduce

[Debug Info_2023-01-18-212658.txt](https://github.com/chrisgrieser/alfred-bibtex-citation-picker/files/10446755/Debug.Info_2023-01-18-212658.txt)

### Debugging Log

```Text
Very strangely, there is no warning in the debug window, all the info is attached above.
```

### Sample BibTeX Entries

```BibTeX
@book{Rang*MaDiYe2002,
  title = {法国史},
  author = {{让{$\cdot$}马蒂耶}},
  translator = {{郑德弟}},
  year = {2002},
  month = sep,
  series = {法汉对照及注释书系},
  publisher = {{上海译文出版社}},
  abstract = {《法国史(法汉对照)》以小见大\textemdash\textemdash 虽不算全面和详尽，但却能为读者提供法兰西民族历史上留下烙印的那些重大事件和重要时期的一个准确的总体印象。犹如一系列里程碑一样，那些影响持久而被认为有开创意义的因数，如一系列事件、社会现象、思想流派，在此得到了特别重视，目的在于让读者搞清这些事件，明白它们在哪些方面影响了历史进程，它们又如何以其独特的方式对法兰西文明的形成作出贡献的。几幅地图和大事年表为《法国史(法汉对照)》提供时空背景。与历史和文化有关的词语均集中在书末的索引之中。    《法国史(法汉对照)》由法国史专家郑德弟教授进行翻译，书中的法汉语言均准确，地道，对已有法语基础，又想通过阅读提高法语水平，并想了解法国历史及知识的读者很有帮助。同时，对进一步提高法语水平和扩大法国知识的大学生及读者亦有很大帮助。},
  isbn = {978-7-5327-2894-7},
  keywords = {_tablet_modified},
  annotation = {7.4/201},
  file = {/Users/yutang/Library/Mobile Documents/com~apple~CloudDocs/Documents/书籍/K-历史、地理/[法]让・马蒂耶_2002_法国史, 郑德弟译.pdf}
}

@book{reggiani2017,
  title = {Digital {{Papyrology I}}: {{Methods}}, {{Tools}} and {{Trends}}},
  shorttitle = {Digital {{Papyrology I}}},
  author = {Reggiani, Nicola},
  year = {2017},
  month = sep,
  publisher = {{De Gruyter}},
  doi = {10.1515/9783110547474},
  isbn = {978-3-11-054747-4},
  langid = {english},
  keywords = {_tablet},
  file = {/Users/yutang/Library/Mobile Documents/com~apple~CloudDocs/Documents/书籍/K-历史、地理/Reggiani_2017_Digital Papyrology I-Digital Papyrology I.pdf}
}

@book{regier2004,
  title = {Book of the {{Sphinx}}},
  author = {Regier, Willis Goth},
  year = {2004},
  month = dec,
  publisher = {{U of Nebraska Press}},
  abstract = {Sought, the Sphinx seems everywhere, whether the guardian of the pyramids on Egypt\&\#39;s Giza plateau or the beautiful man-eater with a deadly riddle, to be approached with awful caution. The Sphinx, that icon painted, sculpted, engraved, and exalted in poetry, fiction, and music, so impressed the philosopher Hegel that he pronounced the creature ?the symbol of the symbolic itself.? With a wealth of illustrations, Book of the Sphinx confirms Hegel\&\#39;s lofty judgment, finding the Sphinx everywhere: in tragedies, paintings, opera, murder mysteries, brothels, bars, and advertisements. \o{} Pursuing the Sphinx through kaleidoscopic sightings and encyclopedic observations, Willis Goth Regier plumbs the symbol\&\#39;s mysteries, conducting the reader down ever more perplexing and intriguing paths. Wonderfully readable, his highly idiosyncratic tour of the ages and the arts leads at last to a conception of the Sphinx that embraces nothing less than all that is unknowable?proving once again that confronting a Sphinx is one of the most dangerous and exhilarating adventures of the imagination.},
  googlebooks = {oOUyS8jODLEC},
  isbn = {978-0-8032-0526-0},
  langid = {english},
  keywords = {Literary Criticism / General,Religion / History,Social Science / Folklore \& Mythology}
}

@book{rengerReceptionsGreekRoman2019,
  title = {Receptions of {{Greek}} and {{Roman Antiquity}} in {{East Asia}}},
  author = {Renger, Almut-Barbara and Fan, Xin},
  year = {2019},
  month = jan,
  publisher = {{BRILL}},
  doi = {10.1163/9789004370715},
  isbn = {978-90-04-37071-5 978-90-04-34012-1},
  langid = {english}
}
```

### Buffer Files

[Archive_2023-01-18 212210.zip](https://github.com/chrisgrieser/alfred-bibtex-citation-picker/files/10446795/Archive_2023-01-18.212210.zip)

### Workflow Configuration

![CleanShot_2023-01-18_212318@2x](https://user-images.githubusercontent.com/84957135/213185330-1ef9cf17-032c-4694-a557-eb55c93fe59d.png)

### Checklist

- [X] I have [updated to the latest version](https://github.com/chrisgrieser/alfred-bibtex-citation-picker/releases/latest) of this workflow.
- [X] I have tried manually reloading the buffer (Alfred keyword `scp`, select `Force Buffer Reload`).

**Comment by u2003** [comment]
Similar stuff also happens when I type cmd+opt+ctrl+shift+enter to open the PDF of an entry with PDFs.

**Comment by chrisgrieser** [comment]
yeah that's a different issue, sounds like #15, which requires some tweaking I'll do when I find the time!

**Comment by chrisgrieser** [comment]
as for the issue with `opt-return`, I cannot reproduce that one and have no idea why it happens to be honest. The only thing I can think of is that you have some setting here which overrides it? 
<img width="1372" alt="image" src="https://user-images.githubusercontent.com/73286100/213223172-07b7fba0-cc20-4d03-b0b2-dbd7bbacf74a.png">

Otherwise, you could try updating Alfred, in case it's an Alfred-related bug

**Comment by u2003** [comment]
Thank you for your reply! I set alt+enter to Search with Finder without much knowledge of it before. 
Now I change it to do nothing, as you can see in the photo:

![CleanShot_2023-01-19 _122450@2x](https://user-images.githubusercontent.com/84957135/213354837-0de7c525-eb7a-4ff2-93fa-134190968ae9.png)

And I restart my Alfred and update to the latest version, yet the opt+enter still doesn't work for me. Really not sure where the problem is.

**Comment by u2003** [comment]
Now I'm certain that should be a bug of Alfred, for the opt+enter causes to jump to Finder on every entry even after I turned off the opt+enter action in Alfred Settings. Yet I have really no idea how to fix this. Just so strange.

**Comment by chrisgrieser** [comment]
Does opt+enter also open Finder with other workflows or is it just with this one?

Do you have any keyboard remapping app running like Karabiner elements?

**Comment by u2003** [comment]
Yeah, I finally find that's remapped by Keyboard Maestro, however it's been a long time that I did not use keyboard maestro and even have it running, so I really didn't notice that. Anyway, thank you so so much for your patience and kind help!!!

**Comment by chrisgrieser** [comment]
glad it's been solved! 😊
