### ISSUE TITLE
[Bug]: library will not load after updating to  V10.0.15

### ISSUE THREAD

**Issue by dstentiford** [chrisgrieser/alfred-bibtex-citation-picker#23]
### Bug Description

I have updated to  V10.0.15. I reconfigured the workflow. I cannot get the library to load. 

### Relevant Screenshot

![Screen Shot 2023-01-20 at 18 59 14](https://user-images.githubusercontent.com/18039161/213840835-d183d99b-391a-4ce7-8d9f-b04102a03fa6.png)
![2023-01-20 18 58 39](https://user-images.githubusercontent.com/18039161/213840848-b66ea6b7-01af-4a9f-be9d-a45c48946f4a.gif)

### Debugging Log

```Text
[19:00:27.279] Logging Started...
[19:00:33.363] Supercharged Citation Picker[Hotkey] Processing complete
[19:00:33.369] Supercharged Citation Picker[Hotkey] Passing output '' to Script Filter
[19:00:33.381] Supercharged Citation Picker[Script Filter] Queuing argument '(null)'
[19:00:33.460] Supercharged Citation Picker[Script Filter] Script with argv '(null)' finished
```

### Sample BibTeX Entries

```BibTeX
@book{1836,
  title = {The {{American Monthly Magazine}}},
  year = {1836},
  publisher = {{M. Bancroft, J. Wiley, and G. and C. and H. Carvill}},
  langid = {english}
}

@article{1862,
  title = {Reclaiming {{Salt Marshes--The Object}} to Be {{Gained}}, and {{How}} to {{Do It}}},
  year = {1862},
  month = sep,
  journal = {American Agriculturist},
  pages = {267}
}

@article{1870,
  title = {Reclaiming {{Green-Harbor Salt-Marsh}}},
  year = {1870},
  month = dec,
  journal = {Hearth \& Home},
  volume = {2},
  number = {53},
  pages = {836}
}
```

### Buffer Files

Note: Github will not allow me to attache the json file. 

[last_version.txt](https://github.com/chrisgrieser/alfred-bibtex-citation-picker/files/10471389/last_version.txt)

### Workflow Configuration

See above

### Checklist

- [X] I have [updated to the latest version](https://github.com/chrisgrieser/alfred-bibtex-citation-picker/releases/latest) of this workflow.
- [X] I have tried manually reloading the buffer (Alfred keyword `scp`, select `Force Buffer Reload`).

**Comment by chrisgrieser** [comment]
Looks like you made a configuration mistake, your bibtex library path does not point to a file ending with `.bib`

**Comment by dstentiford** [comment]
Resolved. Thanks.
