### ISSUE TITLE
[Bug]: Doesn't open item in Zotero anymore

### ISSUE THREAD

**Issue by kenanmike** [chrisgrieser/alfred-bibtex-citation-picker#27]
### Bug Description

As of one of the updates 2 weeks ago, the PDF opens but the feature 'Open Item on Zotero' opens Zotero if it itsn't already open, but either way doesn't select any item on Zotero.

### Relevant Screenshot

Zotero debugging output:

(3)(+0004448): {better-bibtex} +48538 parseLibraryKeyHash { "item": false }

(3)(+0000001): {better-bibtex} +0 getResultsFromParams modified { "objectType": "item", "url": "items/bbt:@koons2023ClassicalTheismNew", "objectID": "bbt:@koons2023ClassicalTheismNew" }

(1)(+0000012): Error: libraryID not provided checkLibraryID@chrome://zotero/content/xpcom/data/dataObjectUtilities.js:55:13 Zotero.DataObject.prototype._setIdentifier@chrome://zotero/content/xpcom/data/dataObject.js:201:15 Zotero.DataObject.prototype._set@chrome://zotero/content/xpcom/data/dataObject.js:151:12 set@chrome://zotero/content/xpcom/data/search.js:70:31 Zotero.API.getResultsFromParams<@chrome://zotero/content/xpcom/api.js:109:11 tryCatcher@resource://zotero/loader.jsm -> resource://zotero/bluebird/util.js:16:16 module.exports/PromiseSpawn.prototype._promiseFulfilled@resource://zotero/loader.jsm -> resource://zotero/bluebird/generators.js:97:18 module.exports/Promise.coroutine/<@resource://zotero/loader.jsm -> resource://zotero/bluebird/generators.js:201:9 From previous event: captureStackTrace@resource://zotero/loader.jsm -> resource://zotero/bluebird/debuggability.js:915:23 CapturedTrace@resource://zotero/loader.jsm -> resource://zotero/bluebird/debuggability.js:807:5 longStackTracesCaptureStackTrace@resource://zotero/loader.jsm -> resource://zotero/bluebird/debuggability.js:482:19 module.exports/Promise.prototype._then@resource://zotero/loader.jsm -> resource://zotero/bluebird/promise.js:261:9 module.exports/Promise.prototype.then@resource://zotero/loader.jsm -> resource://zotero/bluebird/promise.js:154:12 handle/<@file:///Applications/Zotero.app/Contents/Resources/components/zotero-service.js:552:13 addInitCallback@file:///Applications/Zotero.app/Contents/Resources/components/zotero-service.js:452:5 handle@file:///Applications/Zotero.app/Contents/Resources/components/zotero-service.js:551:11

(3)(+0005807): {better-bibtex} +5820 window-loaded chrome://zotero/content/standalone/basicViewer.xul

### To Reproduce

1. Hit the hotkey for Bibtex citation picker & type name of bibliographical item.
2. Hold shift & press enter to 'Open Item in Zotero'
3. Zotero loads if not already open but doesn't select any item anymore.

### Debugging Log

```Text
[10:14:23.124] Supercharged Citation Picker[Hotkey] Processing complete
[10:14:23.129] Supercharged Citation Picker[Hotkey] Passing output '' to Script Filter
[10:14:23.149] Supercharged Citation Picker[Script Filter] Queuing argument '(null)'
[10:14:23.287] Supercharged Citation Picker[Script Filter] Script with argv '(null)' finished
[10:14:23.292] Supercharged Citation Picker[Script Filter] {"items":[{"title":"Biblia patristica 2: Le troisi\\'eme si\\'ecle Orig\\'ene excep…","autocomplete":"patristiques","subtitle":"patristiques et al. (Eds.) 1977   📕","match":"@1977BibliaPatristicaTroisieme Biblia patristica 2: Le troisi\\'eme si\\'ecle Orig\\'ene except\\'e patristiques scientifique calcul 1977   book pdf","arg":"1977BibliaPatristicaTroisieme","icon":{"path":"icons/book.png"},"uid":"1977BibliaPatristicaTroisieme","text":{"copy":"","largetype":"Biblia patristica 2: Le troisi\\'eme si\\'ecle Orig\\'ene except\\'e \n(citekey: 1977BibliaPatristicaTroisieme)"},"quicklookurl":"","mods":{"fn":{"arg":"1977BibliaPatristicaTroisieme_Biblia patristica 2- Le troisi-eme si-ecle Orig"},"ctrl":{"valid":false,"arg":"","subtitle":"⛔️ There is no URL or DOI."}}},(ETC.) [truncated]
[10:14:24.791] Supercharged Citation Picker[Script Filter] Processing complete
[10:14:24.818] Supercharged Citation Picker[Script Filter] Passing output 'koons2023ClassicalTheismNew' to Run Script
[10:14:25.135] Supercharged Citation Picker[Run Script] Processing complete
[10:14:25.153] Supercharged Citation Picker[Run Script] Passing output '' to Post Notification
```

### Sample BibTeX Entries

```BibTeX
@book{koons2023ClassicalTheismNew,
  title = {Classical Theism: New Essays on the Metaphysics of {{God}}},
  shorttitle = {Classical Theism},
  editor = {Koons, Robert C. and Fuqua, Jonathan},
  year = {2023},
  series = {Routledge Studies in the Philosophy of Religion},
  publisher = {{Routledge}},
  address = {{New York, NY}},
  abstract = {"This volume provides a contemporary account of classical theism. It features sixteen original essays from leading scholars that advance the discussion of classical theism in new and interesting directions. It's safe to say that classical theism-the view that God is simple, omniscient, and the greatest possible being-is no longer the assumed view in analytic philosophy of religion. It is often dismissed as being rooted in outdated metaphysical systems of the sort advanced by ancient and medieval philosophers. The main purpose of this volume is twofold: to provide a contemporary account of what classical theism is and to advance the scholarly discussion about classical theism. In Section I, the contributors offer a clear and cutting-edge account of the nature and existence of the God and the historical and theological foundations of classical theism. Section II contains chapters on a variety of topics, such as whether classical theism's doctrine of simplicity needs revision, whether simplicity is compatible with the Christian doctrine of the Incarnation, and whether the hypothesis of a multiplicity of divine ideas is consistent with divine simplicity, among others. Classical Theism will appeal to scholars and advanced students in philosophy of religion who are interested in the nature of God"--},
  isbn = {978-1-03-206064-4 978-1-03-206409-3},
  file = {/Users/michaelbaldwin/OneDrive/Zotero/koons2023ClassicalTheismNew.pdf}
}

@book{koperski2020DivineActionDeterminism,
  title = {Divine Action, Determinism, and the Laws of Nature},
  author = {Koperski, Jeffrey},
  year = {2020},
  publisher = {{Routledge}},
  address = {{Abingdon, Oxon ; New York, NY}},
  abstract = {"A longstanding question at the intersection of science, philosophy, and theology is how God might act, or not, when governing the universe. Many believe that determinism would prevent God from acting at all, since to do so would require violating the laws of nature. However, when a robust view of these laws is coupled with the kind of determinism now used in dynamics, a new model of divine action emerges. This book presents a new approach to divine action beyond the current focus on quantum mechanics and esoteric gaps in the causal order. It bases this approach on two general points. First, that there are laws of nature is not merely a metaphor. Second, laws and physical determinism are now understood in mathematically precise ways that have important implications for metaphysics. The explication of these two claims shows not only that nonviolationist divine action is possible, but there is considerably more freedom available for God to act than current models allow. By bringing a philosophical perspective to an issue often dominated by theologians and scientists, this text redresses an imbalance in the discussion around divine action. It will, therefore, be of keen interest to scholars of Philosophy and Religion, the Philosophy of Science, and Theology"--},
  isbn = {978-0-367-13900-1},
  lccn = {BT135 .K67 2020},
  keywords = {Christianity,Determinism (Philosophy),Philosophy of nature,Providence and government of God,Religion and science},
  file = {/Users/michaelbaldwin/OneDrive/Zotero/koperski2020DivineActionDeterminism.pdf}
}
```

### Buffer Files

There is also a 3rd file in that folder: a 'buffer.json' file I can't upload because github deosn't support that file type.

[change buffer json.txt](https://github.com/chrisgrieser/alfred-bibtex-citation-picker/files/10712853/change.buffer.json.txt)
[last_version.txt](https://github.com/chrisgrieser/alfred-bibtex-citation-picker/files/10712854/last_version.txt)

### Workflow Configuration

<img width="892" alt="195128416-2f2f411e-2a70-4622-a4b2-b0cafd224700" src="https://user-images.githubusercontent.com/85374001/218246048-9ec540b0-c67d-4d4a-abc9-8b87055848d3.png">
<img width="847" alt="195128434-c317885c-b06a-4b7a-847b-093de6e80701" src="https://user-images.githubusercontent.com/85374001/218246052-2aa9c5fc-2023-4c1b-87e6-168f8ed3d066.png">

### Checklist

- [X] I have [updated to the latest version](https://github.com/chrisgrieser/alfred-bibtex-citation-picker/releases/latest) of this workflow.
- [X] I have tried manually reloading the buffer (Alfred keyword `scp`, select `Force Buffer Reload`).

**Comment by tim-hilde** [comment]
Have you tried updating to the most recent version?

**Comment by chrisgrieser** [comment]
oops, forgot to answer to this. Yes, tim_hilde is right, the issue should be fixed in the latest version.

**Comment by kenanmike** [comment]
Ah I had been relying on the automatic updater and so only just seen the readme about updating manually until Alfred Gallery process is complete. Working now —thanks a lot!
