### ISSUE TITLE
Feature Request: Org Mode citation format

### ISSUE THREAD

**Issue by cands** [chrisgrieser/alfred-bibtex-citation-picker#34]
### Feature Requested

Thanks for a splendid workflow! My feature request is to add Org Mode as one of the citation formats. It looks like this: [cite:@citekey]
Please refer to the manual if more information is needed: https://orgmode.org/manual/Citations.html 

### Checklist

- [X] The feature would be useful to more users than just me.

**Comment by chrisgrieser** [comment]
added in latest release 👍

**Comment by chrisgrieser** [comment]
(since the workflow is still pending review for the Alfred gallery, the workflow will not auto-update yet. You'll have to manually download the new release)

**Comment by cands** [comment]
Thanks a lot for implementing this feature.
