### ISSUE TITLE
Feature Request: Support for multiple bib files

### ISSUE THREAD

**Issue by DesBw** [chrisgrieser/alfred-bibtex-citation-picker#35]
### Feature Requested

This is amazing piece of software. I sync my library from Bookends to bib file, as well as from Zotero to another bib file (via Betterbibtex). I use two different reference managers for a number of reasons. 

I would really appreciate if this nifty software can search across all my bib file. 

### Checklist

- [X] The feature would be useful to more users than just me.

**Comment by chrisgrieser** [comment]
Release 11.10 added the ability to add an optional, secondary bibtex library file. https://github.com/chrisgrieser/alfred-bibtex-citation-picker/releases/download/11.10.0/alfred-bibtex-citation-picker.alfredworkflow

(implementing support for *many* bibtex files is going to be kinda tricky though)

Sorry for the late implementation, maintaining software projects as well as working in academia is quite time demanding 😓
