### ISSUE TITLE
[Bug]: Paste Full Bibliography Wait 

### ISSUE THREAD

**Issue by kzssc** [chrisgrieser/alfred-bibtex-citation-picker#37]
### Bug Description

1. Full Bibliography Paste takes a bit long, albeit works without issue upon wait. 

2. Followed Chris's advice [here](https://github.com/chrisgrieser/alfred-bibtex-citation-picker/issues/31#issuecomment-1632335599) to update my pandoc (now ver. 3.1.5) there has been a small decrease in waiting time, from 5-6s to ~4s, I think. 

3. relevance unsure: my library contains over 10k entries

### Debugging Log

```Text
Upon inspecting the debug log a notice that I lot of entries I have doesn't contain URL, I am not sure this is relevant factor the explains the delay as these log were generated when SCP is triggered, *before* anything is typed in. 

I think the only relevant section within the log is: 

[7:49:52.725 am] Supercharged Citation Picker[Script Filter] Processing complete
[7:49:52.808 am] Supercharged Citation Picker[Script Filter] Passing output 'gilabert2023HumanDignitySocial' to Run Script
[7:49:59.368 am] Logging Stopped.

Though, the "logging stopped" was my manual action, not a reflection of the time needed to paste full bibliography.
```

### Sample BibTeX Entries

```BibTeX
@article{1987FacialDiscriminationExtending,
  title = {Facial {{Discrimination}}: {{Extending Handicap Law}} to {{Employment Discrimination}} on the {{Basis}} of {{Physical Appearance}}},
  shorttitle = {Facial {{Discrimination}}},
  date = {1987},
  journaltitle = {Harvard Law Review},
  volume = {100},
  number = {8},
  eprint = {1341199},
  eprinttype = {jstor},
  pages = {2035--2052},
  publisher = {{The Harvard Law Review Association}},
  issn = {0017-811X},
  url = {https://www.jstor.org/stable/1341199},
  urldate = {2022-02-20},
  file = {/Users/vpchris/Zotero/storage/KPE5NJHC/1987 Facial Discrimination - Extending Handicap Law to Employment Discrimination on.pdf;/Users/vpchris/Zotero/storage/MBW4KWMU/1987 Facial Discrimination - Extending Handicap Law to Employment Discrimination on.skim}
}

@book{1992SelfEmploymentPrograms,
  title = {Self {{Employment Programs}} for {{Unemployed Workers}}},
  date = {1992},
  publisher = {{U.S. Dept. of Labor, Employment and Training Administration, Unemployment Insurance Service}},
  location = {{Washington, D.C.}},
  langid = {english},
  annotation = {OCLC: 30034279},
  file = {/Users/vpchris/Zotero/storage/J8X8KID2/Wandner et al 1992 Self Employment Programs for Unemployed Workers.pdf}
}

@article{2000ResourcesLiberalEquality,
  title = {The {{Resources}} of {{Liberal Equality}}},
  date = {2000},
  journaltitle = {Imprints},
  volume = {5},
  pages = {63--82},
  url = {http://www2.warwick.ac.uk/fac/soc/pais/people/clayton/research/theresources_/rle.pdf},
  file = {/Users/vpchris/Zotero/storage/5Z47S47V/2000 The Resources of Liberal Equality.pdf}
}

@book{2002RightSelfEmployment,
  title = {Right to {{Self Employment Bill}}},
  date = {2002},
  publisher = {{House of Parliament, Great Britain}},
  isbn = {978-0-215-70097-1},
  langid = {english},
  keywords = {5th⭐},
  annotation = {OCLC: 1116137684},
  file = {/Users/vpchris/Zotero/storage/7JL54C5T/Great Britain et al 2002 Right to Self Employment Bill.pdf}
}
```

### Buffer Files

[untitled folder 2.zip](https://github.com/chrisgrieser/alfred-bibtex-citation-picker/files/12027614/untitled.folder.2.zip)

### Workflow Configuration

<img width="1292" alt="image" src="https://github.com/chrisgrieser/alfred-bibtex-citation-picker/assets/37780271/8ccd92cc-e2cd-4ad5-b8ec-8637c0b348de">

### Checklist

- [X] I have [updated to the latest version](https://github.com/chrisgrieser/alfred-bibtex-citation-picker/releases/latest) of this workflow.
- [X] I have tried manually reloading the buffer (Alfred keyword `scp`, select `Force Buffer Reload`).

**Comment by chrisgrieser** [comment]
Hmm, can't see anything out of the ordinary here. 

Do you maybe have an old device, low free RAM? If it is the latter, a restart of your mac might help. 

If you use pandoc normally to convert a markdown file with citations, how long does that take?

**Comment by chrisgrieser** [comment]
Also could you attach a full debugging log? That could help pinpoint where the bottleneck might be

**Comment by kzssc** [comment]
> Hmm, can't see anything out of the ordinary here.
> 
> Do you maybe have an old device, or low free RAM? If it is the latter, a restart of your mac might help.

M1 8G ram here. 
> 
> If you use pandoc normally to convert a markdown file with citations, how long does that take?

The pandoc conversion to .docx is instant (contains multiple references), much quicker than the Paste.

**Comment by kzssc** [comment]
much quicker!! 

[2:08:17.888 pm] Supercharged Citation Picker[Script Filter] Processing complete
[2:08:17.960 pm] Supercharged Citation Picker[Script Filter] Passing output 'gilabert2023HumanDignitySocial' to Run Script
[2:08:19.885 pm] Supercharged Citation Picker[Run Script] Processing complete
[2:08:19.898 pm] Supercharged Citation Picker[Run Script] Passing output 'Gilabert, P. (2023). Human Dignity and Social Justice. OUP Oxford.' to Copy to Clipboard

**Comment by chrisgrieser** [comment]
Hmm, it still takes way longer than on my device though (2000ms vs 350ms) 🤔 

But well, guess it's now at least quick enough to work properly with?
