### ISSUE TITLE
Feature Request: exclude comment entry

### ISSUE THREAD

**Issue by noirchen** [chrisgrieser/alfred-bibtex-citation-picker#39]
### Feature Requested

Some bibtex managers, like Jabref, use `@Comment{}` to store information about grouping and other settings. These entries are listed in the picker as empty lines. Is it possible to exclude these comment entries?
<img width="685" alt="Screenshot 2023-07-25 at 22 09 36" src="https://github.com/chrisgrieser/alfred-bibtex-citation-picker/assets/5509175/12f53f1d-bc1c-4b35-b80f-2513dd28cb55">

### Checklist

- [X] The feature would be useful to more users than just me.

**Comment by chrisgrieser** [comment]
Icon added in release 11.7.6 👍
