### ISSUE TITLE
Doppelte Bibliographie

### ISSUE THREAD

**Issue by tim-hilde** [chrisgrieser/alfred-bibtex-citation-picker#4]
### Bug Description

Über die Tastenkombination opt+cmd kann eine Bibliographie erstellt werden. Leider wird sie bei mir immer zwei mal ausgegeben:

https://user-images.githubusercontent.com/44113468/161976960-7b9473b1-321b-46d7-b6ed-4a5c816f3ab1.mov

### To Reproduce

[Debugging Log.txt](https://github.com/chrisgrieser/alfred-bibtex-citation-picker/files/8427000/Debugging.Log.txt)

### Debugging Log

```Text
Siehe "To Reproduce"
```

### Sample BibTeX Entries

```BibTeX
@techreport{deutscherethikratZukunftGenetischenDiagnostik2013,
  type = {{Stellungnahme}},
  title = {{Die Zukunft der genetischen Diagnostik – von der Forschung in die klinische Anwendung}},
  author = {{Deutscher Ethikrat}},
  year = {2013},
  address = {{Berlin}},
  institution = {{Deutscher Ethikrat}},
  langid = {german},
  keywords = {done,Ethik,Genetik,Genetische Diagnostik,Medizin,Medizinethik},
}
```

### Buffer Files

[buffer.txt](https://github.com/chrisgrieser/alfred-bibtex-citation-picker/files/8426970/buffer.txt)
[last_version.txt](https://github.com/chrisgrieser/alfred-bibtex-citation-picker/files/8426986/last_version.txt)

### Workflow Configuration

![image](https://user-images.githubusercontent.com/44113468/161978150-240eca7a-2777-4f6a-9d16-f7b49eca21e0.png)

### Checklist

- [X] I have [updated to the latest version](https://github.com/chrisgrieser/shimmering-obsidian/releases/latest) of this workflow.
- [X] I have tried manually reloading the buffer (Alfred keyword `scp`, select `Force Buffer Reload`).

**Comment by chrisgrieser** [comment]
oops 🙈 
fixed in latest release
