### ISSUE TITLE
[Bug]: pressing paste bibliography is no response

### ISSUE THREAD

**Issue by MartinYuan1995** [chrisgrieser/alfred-bibtex-citation-picker#41]
### Bug Description

All the functions run successfully, except the Paste the full bibliographic entry in the APA 6th Style.

### Debugging Log

```Text
[17:10:41.512] Supercharged Citation Picker[Script Filter] Processing complete
[17:10:41.556] Supercharged Citation Picker[Script Filter] Passing output 'Osborne-2013-It-BritJManage' to Run Script
[17:10:42.468] STDERR: Supercharged Citation Picker[Run Script] Error reading bibliography file /Users/letlifebebeautiful/Documents/Obsidian/Martin Scholar/Reading notes/myarticletoob.bib:
(line 17, column 20):
unexpected '\65306'
[17:10:42.492] Supercharged Citation Picker[Run Script] Processing complete
[17:10:42.493] Supercharged Citation Picker[Run Script] Passing output '' to Copy to Clipboard
```

### Sample BibTeX Entries

```BibTeX
@article{Ahmad-2021-Employees’-PublicAdminRev,
  title = {Employees’ {{Change Support}} in the {{Public Sector}}—{{A Multi}}‐time {{Field Study Examining}} the {{Formation}} of {{Intentions}} and {{Behaviors}}},
  shorttitle = {Employees’ {{Change Support}} in the {{Public Sector}}—{{A}}},
  author = {Ahmad, Ahmad Bayiz and Straatmann, Tammo and Mueller, Karsten and Liu, Bangcheng},
  date = {2021-03},
  journaltitle = {Public Administration Review},
  shortjournal = {Public Admin Rev},
  volume = {81},
  number = {2},
  pages = {231--243},
  issn = {0033-3352, 1540-6210},
  doi = {10.1111/puar.13275},
  url = {https://onlinelibrary.wiley.com/doi/10.1111/puar.13275},
  urldate = {2022-09-20},
  langid = {english},
  file = {/Users/letlifebebeautiful/Zotero/storage/L78A9536/Ahmad-2021-Employees’ Change Support in the Public Sector—A Multi‐time Field Study-《Public Administration Review》.pdf}
}
```

### Buffer Files

.

### Workflow Configuration

<img width="558" alt="image" src="https://github.com/chrisgrieser/alfred-bibtex-citation-picker/assets/47047658/792cc693-bff0-43fb-a051-f58ca4c4a9a0">

### Checklist

- [X] I have [updated to the latest version](https://github.com/chrisgrieser/alfred-bibtex-citation-picker/releases/latest) of this workflow.
- [X] I have tried manually reloading the buffer (Alfred keyword `scp`, select `Force Buffer Reload`).

**Comment by chrisgrieser** [comment]
as the error message notes, there seems to be some issue with your bibliography file:
> [17:10:42.468] STDERR: Supercharged Citation Picker[Run Script] Error reading bibliography file /Users/letlifebebeautiful/Documents/Obsidian/Martin Scholar/Reading notes/myarticletoob.bib: (line 17, column 20): unexpected '\65306'

So open your bibliography file, and at line 17, column 20 there should be some invalid character; probably some special character that pandoc has problems with. Fix the error and then try again, and if it still does not work, open up the debugging log again, if the parser encounters another issue.

This is an issue with your bibtex file / with pandoc in general (pandoc is used to paste the full bibliography). Unfortunately, there is nothing I can do about it on my end.
