### ISSUE TITLE
Feature Request: 

### ISSUE THREAD

**Issue by mjknght** [chrisgrieser/alfred-bibtex-citation-picker#43]
### Feature Requested

I keep the Alfred search bar quite long, and personally, would like the option not to truncate search results – since most of the time I'd be able to read the full title if it weren't for that. Submitting as a feature request in case it is possible! Thanks again for this excellent workflow!

### Checklist

- [X] The feature would be useful to more users than just me.

**Comment by chrisgrieser** [comment]
you already can with this setting: 
![Pasted image 2024-03-03 at 11 41 52@2x](https://github.com/chrisgrieser/alfred-bibtex-citation-picker/assets/73286100/0ab21a37-97cb-439f-a01c-467a4590885e)

**Comment by mjknght** [comment]
Oh, great! Apologies for not spotting that, and thanks for taking time to point it out.
