### ISSUE TITLE
Feature Request: literature notes template

### ISSUE THREAD

**Issue by kzssc** [chrisgrieser/alfred-bibtex-citation-picker#46]
### Feature Requested

(I see that the TODO is embedded in the workflow as is, if this isn't too rude: I hope to give the template function a bump!)

### Checklist

- [X] The feature would be useful to more users than just me.

**Comment by kzssc** [comment]
might consult https://github.com/PKM-er/obsidian-zotlit?tab=readme-ov-file for its function on generating literature note!

**Comment by chrisgrieser** [comment]
yeah, sorry, I personally do not have the need for it, and in more than half a year, there is also not a single other person that has expressed their interest in that feature. Considering that my own time is somewhat limited, I'm gonna have to pass on this feature due to insufficient demand, sorry!
