### ISSUE TITLE
[Bug]: Open Attachment File Broke

### ISSUE THREAD

**Issue by kzssc** [chrisgrieser/alfred-bibtex-citation-picker#49]
### Bug Description

Nothing happens when the open attachment file option is triggered, which isn't registered in the debug log. Other features work correctly.

### Debugging Log

```Text
https://transfer.archivete.am/TbiqJ/Untitled.rtf
```

### Sample BibTeX Entries

```BibTeX
@book{breen2018ExploringRepublicanFreedom,
  title = {{Exploring Republican Freedom: Freedom and Domination}},
  shorttitle = {{Exploring Republican Freedom}},
  author = {Breen, Keith and McBride, Cillian},
  year = {2018},
  month = jan,
  publisher = {Routledge},
  isbn = {978-0-8153-7355-1},
  langid = {Ingl{\'e}s},
  file = {/Users/vpchris/Zotero/storage/JBBK53IT/Breen McBride 2018 Exploring Republican Freedom - Freedom and Domination.pdf}
}

@book{breen2021PoliticsEthicsContemporary,
  title = {The {{Politics}} and {{Ethics}} of {{Contemporary Work}}: {{Whither Work}}?},
  shorttitle = {The {{Politics}} and {{Ethics}} of {{Contemporary Work}}},
  editor = {Breen, Keith and Deranty, Jean-Philippe},
  year = {2021},
  month = jul,
  edition = {1st edition},
  publisher = {Routledge},
  abstract = {Bringing together leading international scholars within the fields of social and political theory and philosophy, this book explores how we should understand work and its role(s) in our lives and wider society.What challenges are posed by work in our changing economy and the new economic forms that are beginning to emerge, and how can we best address these challenges? In what ways do patterns of working, as well as work technologies, shape people's lives within and outside work, in particular their life opportunities and their social and natural environment? How might we organize---or seek to reorganize---workplaces so that the experience of work better reflects our shared ethical ideals and normative principles? This volume examines these vital questions in a comprehensive and systematic manner in order to provide much needed theoretical insight and practical guidance in reflecting on the nature, problems, and possibilities of work currently.This book will be of interest to undergraduate and postgraduate students and established academics in the areas of contemporary political theory and philosophy, social theory, legal philosophy, labour studies, the sociology of work, practical ethics, critical theory, and political activism.},
  langid = {english},
  keywords = {2},
  file = {/Users/vpchris/Zotero/storage/DPSNSB5T/Breen Deranty 2021 The Politics and Ethics of Contemporary Work - Whither Work.pdf}
}

@book{bregman2016UtopiaRealistsCase,
  title = {Utopia for {{Realists}}: {{The Case}} for a {{Universal Basic Income}}, {{Open Borders}}, and a 15-Hour {{Workweek}}},
  shorttitle = {Utopia for {{Realists}}},
  author = {Bregman, Rutger},
  translator = {Manton, Elizabeth},
  year = {2016},
  month = apr,
  edition = {1st edition},
  publisher = {The Correspondent},
  address = {Barcelona},
  isbn = {978-90-825203-0-9},
  langid = {english},
  file = {/Users/vpchris/Zotero/storage/YRIPL7SN/Bregman 2016 Utopia for Realists - The Case for a Universal Basic Income, Open Borders, and a.pdf}
}
```

### Buffer Files

[buffer.json](https://github.com/chrisgrieser/alfred-bibtex-citation-picker/files/15292598/buffer.json)
[last_version.txt](https://github.com/chrisgrieser/alfred-bibtex-citation-picker/files/15292599/last_version.txt)

### Workflow Configuration

<img width="1590" alt="image" src="https://github.com/chrisgrieser/alfred-bibtex-citation-picker/assets/37780271/474fdb00-d9ec-473d-9f5b-b18039efad61">

### Checklist

- [X] I have [updated to the latest version](https://github.com/chrisgrieser/alfred-bibtex-citation-picker/releases/latest) of this workflow.
- [X] I have tried manually reloading the buffer (Alfred keyword `scp`, select `Force Buffer Reload`).

**Comment by chrisgrieser** [comment]
Hmm, it works fine on my end. Thing is, you should either see a "there is no attachment for this entry" message, or get an error notification that the attachment does not exist. Just as safety check:

- do the files exist at the location?
- are you using the correct modifiers (cmd+option+control)? Is maybe some keyboard mapping app (e.g. karabiner elements) changing the modifiers that are actually passed to Alfred here?
- Create a test file at your desktop and set it as attachment `file = {/Users/vchris/Desktop/testfile.txt}` for one of your entries. Does this work?

**Comment by kzssc** [comment]
No notif whatsoever, the alfred bar doesn't even go away. 
1. the files do exist. (I've also tried with other entries - all other functions work, just not this one.) 
2. correct modifiers - when i click cmd+option+control *before* the enter - the subtext does change into "Open Attachment File", just that when i press enter, nothing happens. 
3. I've also tried with a linked file too (as opposed to attached files), nothing happens. 

![IMG_4309](https://github.com/chrisgrieser/alfred-bibtex-citation-picker/assets/37780271/6afff839-953e-492e-b3fb-4d709e3298b7)

**Comment by chrisgrieser** [comment]
> I've also tried with a linked file too (as opposed to attached files), nothing happens.

Please elaborate what you mean by "linked files" – this workflow only opens attachments, pdfs, or URLs (in the browser)?

Did you try the test file as I suggested? `file = {/Users/vchris/Desktop/testfile.txt}`

---

I added some logging to the latest release: https://github.com/chrisgrieser/alfred-bibtex-citation-picker/releases/download/11.15.1/alfred-bibtex-citation-picker.alfredworkflow

In the workflow window, open the debugger again, and change `All information` to `Core information`. Then try once again opening an attachment, and post what appears in the debugging window.

---

**Comment by kzssc** [comment]
sorry, "linked file" is a zotero terminology - i just now remembered that you don't personally use zotero - disregard that comment. (I don't think that matters anyway)

Installed the newer version, manually changed the one of the .bib entries to point to the desktop file, still, no new log appears. (It's literally a blank screen of logs) :|

**Comment by kzssc** [comment]
massive apologies - i got it now - it's a clash of hotkeys with another app on my machine... sorry!!!

**Comment by chrisgrieser** [comment]
all good, glad you could sort it out
