### ISSUE TITLE
Feature Request: Search Retractions API for a Selected Reference

### ISSUE THREAD

**Issue by iandol** [chrisgrieser/alfred-bibtex-citation-picker#5]
### Feature Requested

Endnote just added support for retractions info for cited papers, active at the time you cite in Word. It appears as though this may be a useful feature for your citation picker too. There is at least one open API that uses Pubmed+Crossref combined data: http://openretractions.com — and the other main database appears free for non-commercial use though I didn't find a clear API for it: http://retractiondatabase.org/RetractionSearch.aspx | https://retractionwatch.com 

As far as UI, this could be an option for a selected ref, or something that gets done automatically when you paste a citation. Retractions and an awareness of them are increasingly critical for many scientific fields... Pubpeer comments are another potentially interesting avenue for integration, currently available in Zotero with an API possibly avialable...

- - - - 
Notes:
* Endnote info: https://support.clarivate.com/Endnote/s/article/EndNote-20-Retraction-Alerts?language=en_US
* An interesting summary (as of 2020) by a librarian: https://medium.com/a-academic-librarians-thoughts-on-open-access/understanding-the-current-state-of-retractions-what-you-can-do-about-it-as-an-author-to-avoid-eb63a6632f1e

### Checklist

- [X] The feature would be useful to more users than just me.

**Comment by chrisgrieser** [comment]
That feature looks quite interesting 👀 

However, since retractions aren't really relevant in my field of research, I personally have little use for it, so this is rather a low priority for me personally.

I'll happily accept PRs for this feature though. Since checking the the retractions API should be a rather self-contained script, this would also make a good issue for contributors.

**Comment by chrisgrieser** [comment]
closing this is issue since stale
