### ISSUE TITLE
[Question]: No PDF or literature note detected, what to do?

### ISSUE THREAD

**Issue by siainbuletin** [chrisgrieser/alfred-bibtex-citation-picker#50]
### Bug Description

_I wouldn't actually call this a bug, rather a question on whether I'm doing something wrong._

I have this entry with the citekey `@Campbell2022The-Souls-Tool:` which is generated by BibDesk. I've tried to turn off the colon generation, but I can't seem to find a solution for it. 

![Screenshot 2024-06-03 at 12 30 09](https://github.com/chrisgrieser/alfred-bibtex-citation-picker/assets/97026492/ff756a2e-c139-4d92-a222-573bb69b904a)

Despite the colon not showing up in the preview in this BibDesk pannel, it's present as a separator in every other citation that is generated in it. Of course, I thought it was going to cause some problems with other software. When creating a literature note in Obsidian, the colon gets converted to an underline:

![Screenshot 2024-06-03 at 12 30 25](https://github.com/chrisgrieser/alfred-bibtex-citation-picker/assets/97026492/c061c021-93a8-41b7-bf80-cc661423a15f)

The name of the associated PDF is also generated through Auto-File in BibDesk. The PDF is attached, and it shows as such in BibDesk:

![Screenshot 2024-06-03 at 12 35 57](https://github.com/chrisgrieser/alfred-bibtex-citation-picker/assets/97026492/2eaf29fa-6cba-4117-868a-d1bdd421446b)

The PDF doesn't have a colon nor an underscore.

(I can't take a screenshot of what shows up because of modifier keys) In Alfred, all that shows up are the 🏷 keyword and 📄 abstract icons. 

What can I do to make Alfred recognise the literature note in Obsidian and the PDF that's linked in BibDesk? Is there any rule for the citations?

Also notable information: my PDFs are stored on a server. They can be easily accessed from the button in BibDesk, but not from anywhere else currently.

### Debugging Log

```Text
i can't get the workflow to open when the debugger is turned on. supercharged citation picker just stops showing up
```

### Sample BibTeX Entries

```BibTeX
@book{White1976Plato-on-Knowle,
	author = {White, Nicholas P.},
	booktitle = {Plato on Knowledge and Reality},
	date-added = {2024-05-27 10:42:12 +0300},
	date-modified = {2024-05-27 10:42:55 +0300},
	place = {Indianapolis},
	publisher = {Hacket Publishing Company},
	title = {Plato on Knowledge and Reality},
	year = {1976},
	bdsk-file-1 = {YnBsaXN0MDDSAQIDBFxyZWxhdGl2ZVBhdGhYYm9va21hcmtfED8uLi8uLi8uLi8uLi8uLi9Wb2x1bWVzL2hvbWUvcGFwZXJzL3doaXRlMTk3NnBsYXRvLW9uLWtub3dsZS5wZGZPEQSQYm9va5AEAAAAAAQQMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAsAMAAAcAAAABAQAAVm9sdW1lcwAEAAAAAQEAAGhvbWUGAAAAAQEAAHBhcGVycwAAHAAAAAEBAAB3aGl0ZTE5NzZwbGF0by1vbi1rbm93bGUucGRmEAAAAAEGAAAEAAAAFAAAACAAAAAwAAAACAAAAAQDAACzQQAAAAAAAAAAAAABCgAAEAAAAAEGAABsAAAAfAAAAHwAAAB8AAAACAAAAAAEAABBxgHeuvVMChgAAAABAgAAAQAAAAAAAAAPAAAAAAAAAAAAAAAAAAAAFQAAAAEJAABmaWxlOi8vL1ZvbHVtZXMvaG9tZS8AAAAIAAAABAMAAACgmZl7AwAACAAAAAAEAABBxcmfqPwvYhgAAAABAgAAAAAAAAAAAADvEwAAAQAAAAAAAAAAAAAADQAAAAEBAAAvVm9sdW1lcy9ob21lAAAANAAAAAEJAABzbWI6Ly9zaWFpbmJ1bGV0aW5AU2lhLVN5bm9sb2d5Ll9zbWIuX3RjcC5sb2NhbC9ob21lCAAAAAEJAABmaWxlOi8vLwwAAAABAQAATWFjaW50b3NoIEhECAAAAAQDAAAAUAZeOgAAAAgAAAAABAAAQcX1BKwAAAAkAAAAAQEAAEI1MkJGOUM3LTMxMDAtNEZDNC05N0RDLUY4QUY2Nzc5RDkyMRgAAAABAgAAgQAAAAEAAADvEwAAAQAAAAAAAAAAAAAAAQAAAAEBAAAvAAAAYAAAAP7///8A8AAAAAAAAAcAAAACIAAAEAIAAAAAAAAFIAAAgAEAAAAAAAAQIAAAkAEAAAAAAAARIAAAxAEAAAAAAAASIAAApAEAAAAAAAATIAAAtAEAAAAAAAAgIAAA8AEAAAAAAAAEAAAAAwMAAADwAAAEAAAAAwMAAAAAAAAEAAAAAwMAAAEAAAAUAAAAAQYAAIQCAACQAgAAnAIAAJACAACQAgAA4wAAAAECAAA3OTFjYWZhZDY4NTdlMjE2MTkwMTcyNmU1OTZiZGYwMDlkYWFmMThjM2IwN2MzYTkwYzc0MDY5MDhjMzVmYzY3OzAwOzAwMDAwMDAwOzAwMDAwMDAwOzAwMDAwMDAwOzAwMDAwMDAwMDAwMDAwMjA7Y29tLmFwcGxlLmFwcC1zYW5kYm94LnJlYWQtd3JpdGU7MDE7MzYwMDAwMDI7MDAwMDAwMDAwMDBlOTc2MjswYzsvdm9sdW1lcy9ob21lL3BhcGVycy93aGl0ZTE5NzZwbGF0by1vbi1rbm93bGUucGRmAACoAAAA/v///wEAAAAcAgAADQAAAAQQAABUAAAAAAAAAAUQAACEAAAAAAAAABAQAACsAAAAAAAAAEAQAACcAAAAAAAAAAAgAACoAgAAAAAAAAIgAAAsAQAAAAAAAAUgAADMAAAAAAAAABAgAAAUAAAAAAAAABIgAADsAAAAAAAAABMgAAD8AAAAAAAAACAgAAAMAQAAAAAAAFAgAABEAQAAAAAAAIDwAADEAgAAAAAAAAAIAA0AGgAjAGUAAAAAAAACAQAAAAAAAAAFAAAAAAAAAAAAAAAAAAAE+Q==}}

@incollection{Kelsey2000Recollection-in,
	author = {Kelsey, S.},
	booktitle = {Proceedings of the Boston Area Colloquium in Ancient Philosophy},
	cited-by = {Campbell2022The-Souls-Tool:},
	date-added = {2024-05-26 22:27:45 +0300},
	date-modified = {2024-05-26 22:28:41 +0300},
	pages = {91--121},
	title = {Recollection in the Phaedo},
	volume = {16},
	year = {2000}}
```

### Buffer Files

[buffer.json](https://github.com/user-attachments/files/15532050/buffer.json)
[last_version.txt](https://github.com/user-attachments/files/15532051/last_version.txt)

### Workflow Configuration

![Screenshot 2024-06-03 at 12 46 05](https://github.com/chrisgrieser/alfred-bibtex-citation-picker/assets/97026492/754f9cbc-3878-4f6e-9462-526507735e29)
![Screenshot 2024-06-03 at 12 46 08](https://github.com/chrisgrieser/alfred-bibtex-citation-picker/assets/97026492/f7a53f89-0896-42f9-806f-52d7a39a3b9b)

### Checklist

- [X] I have [updated to the latest version](https://github.com/chrisgrieser/alfred-bibtex-citation-picker/releases/latest) of this workflow.
- [X] I have tried manually reloading the buffer (Alfred keyword `scp`, select `Force Buffer Reload`).

**Comment by chrisgrieser** [comment]
> What can I do to make Alfred recognise the literature note in Obsidian and the PDF that's linked in BibDesk? Is there any rule for the citations?

Well, the literature note and the PDF must be exactly named like the citekey. From the screenshot, it looks like this is not the case for either. So I assume the problem is indeed the citekey.

Unfortunately, I do not use BibDesk, and therefore cannot help much here, sorry. Better ask at some BibDesk forum how to fix that problem? Otherwise, I do not really see much that I can help on my end.
