### ISSUE TITLE
[Bug]: Can't paste a bibliography (error: ./assets/apa-7th.csl not found)

### ISSUE THREAD

**Issue by snam24** [chrisgrieser/alfred-bibtex-citation-picker#51]
### Bug Description

Pasting a bibliography does not work properly. Pandoc is installed with Homebrew.

### Debugging Log

```Text
[12:31:14.085] Supercharged Citation Picker[Script Filter] Processing complete
[12:31:14.125] Supercharged Citation Picker[Script Filter] Passing output 'bolton-scharfstein-1990-theory' to Run Script
[12:31:14.261] STDERR: Supercharged Citation Picker[Run Script] File ./assets/apa-7th.csl not found in resource path
[12:31:14.273] Supercharged Citation Picker[Run Script] Processing complete
[12:31:14.275] Supercharged Citation Picker[Run Script] Passing output '' to Copy to Clipboard
```

### Sample BibTeX Entries

```BibTeX
@article{bolton-scharfstein-1990-theory,
  title = {A {{Theory}} of {{Predation Based}} on {{Agency Problems}} in {{Financial Contracting}}},
  author = {Bolton, Patrick and Scharfstein, David S.},
  date = {1990},
  journaltitle = {The American Economic Review},
  volume = {80},
  number = {1},
  eprint = {2006736},
  eprinttype = {jstor},
  pages = {93--106},
  publisher = {American Economic Association},
  issn = {0002-8282},
  url = {https://www.jstor.org/stable/2006736},
  urldate = {2020-03-02},
  abstract = {By committing to terminate funding if a firm's performance is poor, investors can mitigate managerial incentive problems. These optimal financial constraints, however, encourage rivals to ensure that a firm's performance is poor; this raises the chance that the financial constraints become binding and induce exit. We analyze the optimal financial contract in light of this predatory threat. The optimal contract balances the benefits of deterring predation by relaxing financial constraints against the cost of exacerbating incentive problems.},
  file = {/Users/username/paper_location/B and S, filename.pdf}
}
```

### Buffer Files

[buffer.json](https://github.com/user-attachments/files/16352486/buffer.json)
[last_version.txt](https://github.com/user-attachments/files/16352487/last_version.txt)

### Workflow Configuration

![Screenshot_2024-07-23-12_40_24_vW2lHk](https://github.com/user-attachments/assets/dd6b6453-54b7-490b-b834-13aeaabd996b)

### Checklist

- [X] I have [updated to the latest version](https://github.com/chrisgrieser/alfred-bibtex-citation-picker/releases/latest) of this workflow.
- [X] I have tried manually reloading the buffer (Alfred keyword `scp`, select `Force Buffer Reload`).

**Comment by chrisgrieser** [comment]
thanks, fixed.

available in the Alfred Gallery in 1-2 days, or directly by downloading the latest release here

https://github.com/chrisgrieser/alfred-bibtex-citation-picker/releases/download/11.15.2/alfred-bibtex-citation-picker.alfredworkflow

**Comment by snam24** [comment]
Hi @chrisgrieser, I updated the workflow and restarted the Alfred app, but the problem persists with the same error. Will you please take a look?

**Comment by chrisgrieser** [comment]
Weird, for some reason the fix wasn't properly saved correctly. Released again, should work now.
