### ISSUE TITLE
Feature Request: literature note opens in new tab in obsidian 

### ISSUE THREAD

**Issue by kzssc** [chrisgrieser/alfred-bibtex-citation-picker#54]
### Feature Requested

it'd be great if the literature note can be opened in a new tab (perhaps devise a toggle to suit different usages?).

### Checklist

- [X] The feature would be useful to more users than just me.

**Comment by chrisgrieser** [comment]
currently, the[ Obsidian URI](https://help.obsidian.md/Extending+Obsidian/Obsidian+URI) does not allow specifying things like opening in a new tab. So the only way to do this would to use an extra Obsidian plugin as requirement, which I'd like to avoid since every use would need to add this as requirement, even if they do not use such a feature.

I'd suggest opening a feature request in the Obsidian forum for making the URI more flexible. Until then, I will unfortunately have to refrain from implementing this feature.

**Comment by kzssc** [comment]
another obsidian related issue: _sometimes_, when creating+opening a new literature note (i.e. when there's no preexisting note), obsidian reports an error of file not found. I guess that it might be due to that obsidian is acting too quickly (prior to the creation of the .md)? 

This no longer happens when the same command is triggered again. And this doesn't happen every time. 

Any insight on what might be the cause?

**Comment by chrisgrieser** [comment]
That's due to Obsidian not picking up a newly create file yet. Again, there is little I can do on my end about this, I think.

**Comment by kzssc** [comment]
i'm trialing in non-obsidian environment, perhaps introduce an option to choose the default editor? 

the replacement script i'm toying: 

#!/usr/bin/env osascript -l JavaScript
ObjC.import("stdlib");
const app = Application.currentApplication();
app.includeStandardAdditions = true;
//───────────────────────────────────────────────────────────────────────────

/** @type {AlfredRun} */
// biome-ignore lint/correctness/noUnusedVariables: Alfred run
function run(argv) {
	const citekey = argv.join("");
	const literatureNotePath =
		$.getenv("literature_note_folder").replace(/^~/, app.pathTo("home folder")) +
		`/${citekey}.md`;

	// Create literature note
	const literatureNoteExists = Application("Finder").exists(Path(literatureNotePath));
	if (!literatureNoteExists) {
		const template = "---\ntags: \naliases:\n---\n\n";
		app.doShellScript(`echo '${template}' > '${literatureNotePath}'`);
	}

	// Always open with the system-default app
	app.doShellScript(`open '${literatureNotePath}'`);
}

**Comment by chrisgrieser** [comment]
If you want a new feature, please open a feature request
