### ISSUE TITLE
Feature Request: Paste formatted citation

### ISSUE THREAD

**Issue by Ashley1985** [chrisgrieser/alfred-bibtex-citation-picker#57]
### Feature Requested

The option to paste the already 'formatted citation' when not using Pandoc would be a useful addition which fixes a number of citation programs that are locked to Word & Google Docs. 

### Checklist

- [X] The feature would be useful to more users than just me.

**Comment by chrisgrieser** [comment]
Good idea. Using formatted single entries is now available as a special citation format, you can set it via `scp` → `Change citation format` → `formatted single entry`. Note that this also requires [pandoc](http://pandoc.org/installing.html) to be installed on your device.

Available in the Alfred Gallery in 1-2 days, or directly by downloading the latest release here: https://github.com/chrisgrieser/alfred-bibtex-citation-picker/releases/download/11.16.0/alfred-bibtex-citation-picker.alfredworkflow
