### ISSUE TITLE
Feature Request: Pick own bibliography style

### ISSUE THREAD

**Issue by laleleoni** [chrisgrieser/alfred-bibtex-citation-picker#7]
### Feature Requested

I love this workflow - thanks so much for the amazing work! Being able to paste the full bibliographic entry into emails is a very practical feature, however doing so in APA 6th has a big disadvantage for someone working in German : Capitalization in titles is not working. Can this be changed in the script (or a different bibliography style be chosen), and if yes, how so? Since I don't understand the whole workflow I don't want to temper with it...

### Checklist

- [X] The feature would be useful to more users than just me.

**Comment by chrisgrieser** [comment]
Thank you!

> however doing so in APA 6th has a big disadvantage for someone working in German : Capitalization in titles is not working

Actually, that isn't a problem with APA 6th, and would occur with any other citation style as well. [In the bibtex format, you needs curly braces `{}` to preserve capitalization.](https://texfaq.org/FAQ-capbibtex)

So you rather need to adjust some setting for the tool you use to generate the bibtex file – this is unfortunately not something I can change on my end, sorry!

**Comment by laleleoni** [comment]
Hi Chris, thanks a lot - that's helpful (I wasn't aware, but it seems like
Bookends can do that). On another note: the pasting function using ⌘⌥ + ↵
has stopped working altogether for me, as of today... Did you change
anything else?

**Comment by chrisgrieser** [comment]
> On another note: the pasting function using ⌘⌥ + ↵
has stopped working altogether for me, as of today... Did you change
anything else?

hmm, well I did push some updates today, but `⌘⌥ + ↵` works without any issue on my end? 🤔 

Try updating / reinstalling the workflow, there have been a lot of smaller updates today. and if the issue still persists, open a bug report? (reason being that the bug report formula includes a lot of info on troubleshooting.)

**Comment by laleleoni** [comment]
Problem solved ! I updated but it was apparently due to a missing citekey,
as I learnt from the debugger. Thanks for the hint (hadn't used it before,
still very new to Alfred)

**Comment by laleleoni** [comment]
PS - sorry to bother you once more but I still have a question about
capitalization : Do you really think it's best for someone compiling a
bibliography in German to wrap all titles in double { } ? Since LaTeX
bibliography styles can handle capitalization independent of the bib file,
I'm hesitant to configure Bookends so that all my titles will be wrapped in
curly braces in the bib file, because that will limit the customizability I
have with bibliography styles... I am assuming Pandoc can't do that.  Is
that correct ?

**Comment by chrisgrieser** [comment]
tbh, I have no idea about Latex, since I only use pandoc and as far as know, the curly braces do not matter for pandoc (except as information for capitalization)? 😕 

sorry, I use pandoc and markdown exactly because latex is a bit over my head 🙈

**Comment by laleleoni** [comment]
Ha - I thought it was the opposite way around - LaTeX definitely being
easier than what you're doing. Thanks in any case !
