### ISSUE TITLE
Enable option to generate MMD citations

### ISSUE THREAD

**Issue by karkraeg** [chrisgrieser/alfred-bibtex-citation-picker#8]
### Feature Requested

Would it be possible to add an option to generate citations like `[#Helms2008]` instead `[@Helms2008]` and `[25][#Helms2008]` instead `[@Helms2008, p. 25]` - see https://fletcher.github.io/MultiMarkdown-6/syntax/citation.html ?

Thanks!

### Checklist

- [X] The feature would be useful to more users than just me.

**Comment by karkraeg** [comment]
If you could point me to where I could adjust this for me that would be great ✌️

**Comment by chrisgrieser** [comment]
Hi, the part responsible for the citation format is unfortunately implemented mostly in Alfred itself instead of a proper code file (cause it requires looping through Alfred modals itself for multiple citations).

This isn't impossible to change, but at least a bit inflexible and therefore more time-intensive to change. (Which is also why I haven't implemented #1 yet.) It's the teal-blue part if you want to give it a try yourself.
<img width="1211" alt="Pasted image 2022-05-17 17 12 46" src="https://user-images.githubusercontent.com/73286100/168846430-2f848a37-adcf-487a-8317-4d5787aecc20.png">

**Comment by karkraeg** [comment]
I think it’s the way the bibtex data is written into the buffer.json? If I manually change to `"arg": "#AhlersJacke2016",` it gets pasted the way I want

**Comment by karkraeg** [comment]
Yeah, you need to change https://github.com/chrisgrieser/alfred-bibtex-citation-picker/blob/96570c651b04b8cc9e5d83ca25ff28a3078df848/scripts/buffer_writer.js#L177 to `"arg": "#" + citekey,` then delete the buffer.json in `/Users/YOURUSER/Library/Application Support/Alfred/Workflow Data/de.chris-grieser.alfred-bibtex-citation-picker/buffer.json` and then customize this setting:

<img width="944" alt="image" src="https://user-images.githubusercontent.com/8436596/168883339-4510e640-72ef-4843-bdc9-cd17d05fa944.png">

**Comment by chrisgrieser** [comment]
yep, that's pretty much it. If I find the time, I'll implement a setting for this (and Latex in #1), but for now, I have a bunch of deadlines....

**Comment by karkraeg** [comment]
cool! normal citations work, but citations with page now look like `[#Helms2008, p. 625]` where it should be `[625][#Helms2008]`

**Comment by chrisgrieser** [comment]
boy, having page numbers *before* the citekey is really weird. Lemme look how to switch the order, as well.

**Comment by chrisgrieser** [comment]
okay, these two settings have been added to version 9.1.0. Have a look whether they are sufficient for MMD citations?
![image](https://user-images.githubusercontent.com/73286100/169468416-d1ab2fe8-d7e8-46a8-82fb-ff5430016cfc.png)

**Comment by karkraeg** [comment]
Using this options it woks, thanks!

![grafik](https://user-images.githubusercontent.com/8436596/169468965-5daa2e6f-8233-45f9-93a7-9be092609ea8.png)

**Comment by chrisgrieser** [comment]
are you sure? Like in the post before, you mentioned that in MMD, the page number comes before the citekey, and in the screenshot you are sharing, you left `_format_page_before_citekey` as `false` 😝

**Comment by karkraeg** [comment]
yeah, that seems to be a bug 🙈 or rather I did try it this way and then it worked:

https://user-images.githubusercontent.com/8436596/169474442-73e8a1cb-ad61-48b4-94f6-9bec177044a2.mov

**Comment by chrisgrieser** [comment]
oops, yes, I mixed up true and false on my side 🙈

**Comment by chrisgrieser** [comment]
should be fixed.

**Comment by chrisgrieser** [comment]
thanks for your input. One can now conveniently change the citation format via `scp` 🙂 

<img width="1060" alt="Pasted image 2022-05-20 12 02 32" src="https://user-images.githubusercontent.com/73286100/169505105-34399155-8e4c-4a92-bb97-3e9671327875.png">
<img width="1056" alt="Pasted image 2022-05-20 12 02 54" src="https://user-images.githubusercontent.com/73286100/169505176-48f9fa9d-2c78-490f-9341-19cc2918b4e3.png">

**Comment by karkraeg** [comment]
Thats nice!
